[package]
name = "json-rpc-example-program"
version = "2.3.6"
edition = "2021"

[features]
# This was needed for ci
dummy-for-ci-check = []
frozen-abi = []

[dependencies]
borsh = "0.9"
solana-account-info = "2.2.1"
solana-program-entrypoint = "2.2.1"
solana-msg = "2.2.1"
solana-pubkey = "2.3.0"

[lib]
name = "program"
crate-type = ["cdylib", "lib"]

[workspace]
